// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovieOneToMany.Data;

#nullable disable

namespace MvcMovieOneToMany.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20241208093145_Relation")]
    partial class Relation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcMovieOneToMany.Models.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenreId");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MvcMovieOneToMany.Models.Movie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MvcMovieOneToMany.Models.MovieDetails", b =>
                {
                    b.Property<Guid>("MovieDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieDetailsId");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("MoviesDetails");
                });

            modelBuilder.Entity("MvcMovieOneToMany.Models.Genre", b =>
                {
                    b.HasOne("MvcMovieOneToMany.Models.Movie", "Movie")
                        .WithOne("Genre")
                        .HasForeignKey("MvcMovieOneToMany.Models.Genre", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MvcMovieOneToMany.Models.MovieDetails", b =>
                {
                    b.HasOne("MvcMovieOneToMany.Models.Movie", "Movie")
                        .WithOne("MovieDetails")
                        .HasForeignKey("MvcMovieOneToMany.Models.MovieDetails", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MvcMovieOneToMany.Models.Movie", b =>
                {
                    b.Navigation("Genre")
                        .IsRequired();

                    b.Navigation("MovieDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
